# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2020-04-29 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200427_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_due',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
