# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2020-04-30 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_shipping_due'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('department', models.CharField(max_length=100, null=True)),
                ('hours', models.FloatField(null=True)),
                ('comment', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='amount_paid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='arrival_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
