# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2020-05-04 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200430_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='anodizing_completed',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='extrusion_completed',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fabrication_completed',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_completed',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
