# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2020-05-20 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200504_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capitalinjection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('capital_injection_amount', models.FloatField(null=True)),
                ('capital_injection_comment', models.TextField(null=True)),
            ],
        ),
    ]
