# Generated by Django 2.0 on 2020-05-21 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_capitalinjection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Extrusion',
        ),
        migrations.RemoveField(
            model_name='order',
            name='purchase_order',
        ),
        migrations.AddField(
            model_name='order',
            name='die_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
