# Generated by Django 2.0 on 2020-05-21 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20200520_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_received',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
