# Generated by Django 2.0 on 2020-05-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20200521_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='part_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='die_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_received',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
