# Generated by Django 2.0 on 2020-05-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_order_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billaddress',
            name='bill_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customername',
            name='customer_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shipaddress',
            name='ship_number',
            field=models.CharField(max_length=50),
        ),
    ]
