# Generated by Django 2.0 on 2020-05-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20200521_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='workorder_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
